export enum Priority {
    High        = 0,
    NormalHigh  = 1,
    Normal      = 2,
    NormalLow   = 3,
    Low         = 4,
}

export const reactionTable: IReactionTable = {
    ["XUH2O"]: ["UH2O", "X"],
    ["XUHO2"]: ["UHO2", "X"],
    ["XKH2O"]: ["KH2O", "X"],
    ["XKHO2"]: ["KHO2", "X"],
    ["XLH2O"]: ["LH2O", "X"],
    ["XLHO2"]: ["LHO2", "X"],
    ["XZH2O"]: ["ZH2O", "X"],
    ["XZHO2"]: ["ZHO2", "X"],
    ["XGH2O"]: ["GH2O", "X"],
    ["XGHO2"]: ["GHO2", "X"],

    ["UH2O"]: ["UH", "OH"],
    ["UHO2"]: ["UO", "OH"],
    ["KH2O"]: ["KH", "OH"],
    ["KHO2"]: ["KO", "OH"],
    ["LH2O"]: ["LH", "OH"],
    ["LHO2"]: ["LO", "OH"],
    ["ZH2O"]: ["ZH", "OH"],
    ["ZHO2"]: ["ZO", "OH"],
    ["GH2O"]: ["GH", "OH"],
    ["GHO2"]: ["GO", "OH"],

    ["UH"]: ["U", "H"],
    ["UO"]: ["U", "O"],
    ["KH"]: ["K", "H"],
    ["KO"]: ["K", "O"],
    ["LH"]: ["L", "H"],
    ["LO"]: ["L", "O"],
    ["ZH"]: ["Z", "H"],
    ["ZO"]: ["Z", "O"],
    ["GH"]: ["G", "H"],
    ["GO"]: ["G", "O"],

    ["OH"]: ["O", "H"],
    ["ZK"]: ["Z", "K"],
    ["UL"]: ["U", "L"],
    ["G"]: ["ZK", "UL"],
}