export const LAB_STATE = {
    WORKING: 'working',
    BOOST: 'boost',
    IN_RESOURCE: 'inResource',
    OUT_RESOURCE: 'outResource',
    INIT: 'init',
    GET_TARGET: 'getTarget',
};

export const ROOM_TRANSFER_TASK = {
    LAB_IN: 'labIn',
    LAB_OUT: 'labOut',
    BOOST_GET_RESOURCE: 'boostGetResource',
    BOOST_GET_ENERGY: 'boostGetEnergy',
    BOOST_CLEAR: 'boostClear',
};

export const LAB_TRANSFER_TASK = {
    LAB_IN: 'labIn',
    LAB_OUT: 'labOut',
    LAB_IN_ENERGY: 'labInEnergy',
};

export const BOOST_STATE = {
    BOOST_GET_RESOURCE: 'boostGetResource',         // 获取准备 boost 的资源
    BOOST_GET_ENERGY: 'boostGetEnergy',             // 填充 lab 的能量
    BOOST_WAIT: 'boostWait',                        // 等待
    BOOST_CLEAR: 'boostClear',                      // boost 结束，把用到的资源放回 terminal
}

export const BOOST_RESOURCE = {
    war: [
        // attack
        RESOURCE_CATALYZED_GHODIUM_ACID,
        // heal
        RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE,
        // move
        RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE,
        // tough
        RESOURCE_CATALYZED_GHODIUM_ALKALIDE,
        // ranged attack
        RESOURCE_CATALYZED_KEANIUM_ALKALIDE,
    ],
    upgrade: [
        // 二级化合物
        // RESOURCE_GHODIUM_ACID,
        // 三级化合物
        RESOURCE_CATALYZED_GHODIUM_ACID,
    ],
}

export const labTarget = [
    // 基础化合物
    { target: RESOURCE_UTRIUM_LEMERGITE, number: 2000},
    { target: RESOURCE_ZYNTHIUM_KEANITE, number: 2000},
    { target: RESOURCE_HYDROXIDE, number: 2000},
    { target: RESOURCE_GHODIUM, number: 2000},

    // attack
    { target: RESOURCE_CATALYZED_UTRIUM_ACID, number: 6000},  
    { target: RESOURCE_UTRIUM_ACID, number: 3000}, 
    { target: RESOURCE_UTRIUM_HYDRIDE, number: 1000},

    // ranged attack
    { target: RESOURCE_CATALYZED_KEANIUM_ALKALIDE, number: 6000},
    { target: RESOURCE_KEANIUM_ALKALIDE, number: 3000}, 
    { target: RESOURCE_KEANIUM_OXIDE, number: 1000},

    // move
    { target: RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE, number: 6000}, 
    { target: RESOURCE_ZYNTHIUM_ALKALIDE, number: 1000}, 
    { target: RESOURCE_ZYNTHIUM_OXIDE, number: 1000},

    // tough
    { target: RESOURCE_CATALYZED_GHODIUM_ALKALIDE, number: 6000}, 
    { target: RESOURCE_GHODIUM_ALKALIDE, number: 2000}, 
    { target: RESOURCE_GHODIUM_OXIDE, number: 1000},

    // heal
    { target: RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE, number: 6000},
    { target: RESOURCE_LEMERGIUM_ALKALIDE, number: 2000}, 
    { target: RESOURCE_LEMERGIUM_OXIDE, number: 1000},

    // dismantle
    { target: RESOURCE_CATALYZED_ZYNTHIUM_ACID, number: 4000},
    { target: RESOURCE_ZYNTHIUM_ACID, number: 1000}, 
    { target: RESOURCE_ZYNTHIUM_HYDRIDE, number: 1000},

    // upgrader
    { target: RESOURCE_CATALYZED_GHODIUM_ACID, number: 4000},   
    { target: RESOURCE_GHODIUM_ACID, number: 1000}, 
    { target: RESOURCE_GHODIUM_HYDRIDE, number: 1000},

    // { target: RESOURCE_CATALYZED_UTRIUM_ALKALIDE, number: 3000},    // harvester
    // { target: RESOURCE_CATALYZED_KEANIUM_ACID, number: 3000},       // carry
    // { target: RESOURCE_CATALYZED_LEMERGIUM_ACID, number: 3000},     // repairer

    // // 二级化合物
    // { target: RESOURCE_UTRIUM_ALKALIDE, number: 3000}, 
    // { target: RESOURCE_KEANIUM_ACID, number: 3000}, 
    // { target: RESOURCE_LEMERGIUM_ACID, number: 3000}, 

    // // 一级化合物
    // { target: RESOURCE_UTRIUM_OXIDE, number: 3000},
    // { target: RESOURCE_KEANIUM_HYDRIDE, number: 3000},
    // { target: RESOURCE_LEMERGIUM_HYDRIDE, number: 3000},
];

export const reactionResource = {
    // 三级化合物
    [RESOURCE_CATALYZED_UTRIUM_ACID]: [RESOURCE_UTRIUM_ACID, RESOURCE_CATALYST],
    [RESOURCE_CATALYZED_UTRIUM_ALKALIDE]: [RESOURCE_UTRIUM_ALKALIDE, RESOURCE_CATALYST],
    [RESOURCE_CATALYZED_KEANIUM_ACID]: [RESOURCE_KEANIUM_ACID, RESOURCE_CATALYST],
    [RESOURCE_CATALYZED_KEANIUM_ALKALIDE]: [RESOURCE_KEANIUM_ALKALIDE, RESOURCE_CATALYST],
    [RESOURCE_CATALYZED_LEMERGIUM_ACID]: [RESOURCE_LEMERGIUM_ACID, RESOURCE_CATALYST],
    [RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE]: [RESOURCE_LEMERGIUM_ALKALIDE, RESOURCE_CATALYST],
    [RESOURCE_CATALYZED_ZYNTHIUM_ACID]: [RESOURCE_ZYNTHIUM_ACID, RESOURCE_CATALYST],
    [RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE]: [RESOURCE_ZYNTHIUM_ALKALIDE, RESOURCE_CATALYST],
    [RESOURCE_CATALYZED_GHODIUM_ACID]: [RESOURCE_GHODIUM_ACID, RESOURCE_CATALYST],
    [RESOURCE_CATALYZED_GHODIUM_ALKALIDE]: [RESOURCE_GHODIUM_ALKALIDE, RESOURCE_CATALYST],

    // 二级化合物
    [RESOURCE_UTRIUM_ACID]: [RESOURCE_UTRIUM_HYDRIDE, RESOURCE_HYDROXIDE],
    [RESOURCE_UTRIUM_ALKALIDE]: [RESOURCE_UTRIUM_OXIDE, RESOURCE_HYDROXIDE],
    [RESOURCE_KEANIUM_ACID]: [RESOURCE_KEANIUM_HYDRIDE, RESOURCE_HYDROXIDE],
    [RESOURCE_KEANIUM_ALKALIDE]: [RESOURCE_KEANIUM_OXIDE, RESOURCE_HYDROXIDE],
    [RESOURCE_LEMERGIUM_ACID]: [RESOURCE_LEMERGIUM_HYDRIDE, RESOURCE_HYDROXIDE],
    [RESOURCE_LEMERGIUM_ALKALIDE]: [RESOURCE_LEMERGIUM_OXIDE, RESOURCE_HYDROXIDE],
    [RESOURCE_ZYNTHIUM_ACID]: [RESOURCE_ZYNTHIUM_HYDRIDE, RESOURCE_HYDROXIDE],
    [RESOURCE_ZYNTHIUM_ALKALIDE]: [RESOURCE_ZYNTHIUM_OXIDE, RESOURCE_HYDROXIDE],
    [RESOURCE_GHODIUM_ACID]: [RESOURCE_GHODIUM_HYDRIDE, RESOURCE_HYDROXIDE],
    [RESOURCE_GHODIUM_ALKALIDE]: [RESOURCE_GHODIUM_OXIDE, RESOURCE_HYDROXIDE],

    // 一级化合物
    [RESOURCE_UTRIUM_HYDRIDE]: [RESOURCE_HYDROGEN, RESOURCE_UTRIUM],
    [RESOURCE_UTRIUM_OXIDE]: [RESOURCE_OXYGEN, RESOURCE_UTRIUM],
    [RESOURCE_KEANIUM_HYDRIDE]: [RESOURCE_HYDROGEN, RESOURCE_KEANIUM],
    [RESOURCE_KEANIUM_OXIDE]: [RESOURCE_OXYGEN, RESOURCE_KEANIUM],
    [RESOURCE_LEMERGIUM_HYDRIDE]: [RESOURCE_HYDROGEN, RESOURCE_LEMERGIUM],
    [RESOURCE_LEMERGIUM_OXIDE]: [RESOURCE_OXYGEN, RESOURCE_LEMERGIUM],
    [RESOURCE_ZYNTHIUM_HYDRIDE]: [RESOURCE_HYDROGEN, RESOURCE_ZYNTHIUM],
    [RESOURCE_ZYNTHIUM_OXIDE]: [RESOURCE_OXYGEN, RESOURCE_ZYNTHIUM],
    [RESOURCE_GHODIUM_HYDRIDE]: [RESOURCE_HYDROGEN, RESOURCE_GHODIUM],
    [RESOURCE_GHODIUM_OXIDE]: [RESOURCE_OXYGEN, RESOURCE_GHODIUM],

    // 基础化合物
    [RESOURCE_HYDROXIDE] : [RESOURCE_OXYGEN, RESOURCE_HYDROGEN],
    [RESOURCE_ZYNTHIUM_KEANITE]: [RESOURCE_ZYNTHIUM, RESOURCE_KEANIUM],
    [RESOURCE_UTRIUM_LEMERGITE]: [RESOURCE_UTRIUM, RESOURCE_LEMERGIUM],
    [RESOURCE_GHODIUM]: [RESOURCE_ZYNTHIUM_KEANITE, RESOURCE_UTRIUM_LEMERGITE],
}